apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: dev-app-core-com-backend-binding
  namespace: devops-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.project.http_url)
    - name: gitusername
      value: $(body.user_username)
    - name: project-name
      value: $(body.project.name)

---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: test-app-core-com-backend-binding
  namespace: devops-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.object_attributes.merge_commit_sha)
    - name: gitrepositoryurl
      value: $(body.project.http_url)
    - name: gitusername
      value: $(body.user.username)
    - name: project-name
      value: $(body.project.name)

---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: prd-mattermost-app-core-com-backend-binding
  namespace: devops-pipelines
spec:
  params:
    - name: build-id
      value: $(extensions.build-id)
    - name: gitrevision
      value: $(extensions.gitrevision)
    - name: rollout-strategy
      value: $(extensions.rollout-strategy)
    - name: mattermost-username
      value: $(body.user_name)
    - name: mattermost-team
      value: $(body.team_domain)
    - name: mattermost-channel
      value: $(body.channel_name)

