apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pl-app-core-com-backend
  namespace: devops-pipelines
spec:
  finally:
    - name: clean-workspace
      params:
        - name: subdirectory
          value: $(params.clone-to-directory)
      taskRef:
        kind: Task
        name: clean-workspace
      workspaces:
        - name: output
          workspace: source
    - name: report-result
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
      taskRef:
        kind: Task
        name: mm-send-result
  params:
    - name: build-stage
      type: string
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: git-username
      type: string
    - name: clone-to-directory
      type: string
    - name: image-url
      type: string
    - name: spring-profile
      type: string
    - name: gitops-url
      type: string
    - name: gitops-revision
      type: string
    - name: gitops-path
      type: string
    - name: deploy-manifest
      type: string
    - name: sonar-project-key
      type: string
    - name: rollout-strategy
      type: string
    - name: pipelinerun-name
      type: string
    - name: mm-channel
      type: string
  tasks:
    - name: notify-pipeline-start
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
      taskRef:
        kind: Task
        name: mm-notify-start
    - name: generate-id
      params:
        - name: base-version
          value: $(params.build-stage)
      taskRef:
        kind: Task
        name: generate-build-id
    - name: clone-sources
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.clone-to-directory)
      runAfter:
        - generate-id
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: source-scan
      params:
        - name: SONAR_PROJECT_KEY
          value: $(params.sonar-project-key)
        - name: SOURCE_TO_SCAN
          value: $(params.clone-to-directory)
      runAfter:
        - clone-sources
      taskRef:
        kind: Task
        name: sonarqube-scan
      workspaces:
        - name: source
          workspace: source
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
        - name: DIRECTORY
          value: $(params.clone-to-directory)
        - name: spring-profile
          value: $(params.spring-profile)
      runAfter:
        - clone-sources
      taskRef:
        kind: Task
        name: jib-maven
      workspaces:
        - name: source
          workspace: source
    - name: image-scan
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: trivy-scan
      workspaces:
        - name: manifest-dir
          workspace: manifest-dir
    - name: update-gitops
      params:
        - name: git-revision
          value: $(params.git-revision)
        - name: gitops-revision
          value: $(params.gitops-revision)
        - name: deploy-manifest
          value: $(params.deploy-manifest)
        - name: gitops-path
          value: $(params.gitops-path)
        - name: gitops-url
          value: $(params.gitops-url)
        - name: rollout-strategy
          value: $(params.rollout-strategy)
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(tasks.generate-id.results.build-id)
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: update-gitops
      workspaces:
        - name: gitops
          workspace: gitops
  workspaces:
    - name: source
    - name: gitops
    - name: manifest-dir

---

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pl-app-core-com-backend-build
  namespace: devops-pipelines
spec:
  finally:
    - name: clean-workspace
      params:
        - name: subdirectory
          value: $(params.clone-to-directory)
      taskRef:
        kind: Task
        name: clean-workspace
      workspaces:
        - name: output
          workspace: source
    - name: report-result
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
      taskRef:
        kind: Task
        name: mm-send-result
    - name: save-pipelinerun-logs
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: pipeline-name
          value: $(params.pipeline-name)
      taskRef:
        kind: Task
        name: tekton-logging
      workspaces:
        - name: hro-tekton-logs
          workspace: hro-tekton-logs
  params:
    - name: build-stage
      type: string
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: git-username
      type: string
    - name: clone-to-directory
      type: string
    - name: image-url
      type: string
    - name: spring-profile
      type: string
    - name: red-project-name
      type: string
    - name: red-issue-tracker
      type: string
    - name: application-name
      type: string
    - name: last-commit-message
      type: string
    - name: merge-title
      type: string
    - name: merge-description
      type: string
    - name: merge-date
      type: string
    - name: pipelinerun-name
      type: string
    - name: pipeline-name
      type: string
    - name: mm-channel
      type: string
  tasks:
    - name: notify-pipeline-start
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
      taskRef:
        kind: Task
        name: mm-notify-start
    - name: generate-id
      params:
        - name: base-version
          value: $(params.build-stage)
      taskRef:
        kind: Task
        name: generate-build-id
    - name: clone-sources
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.clone-to-directory)
      runAfter:
        - generate-id
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
        - name: DIRECTORY
          value: $(params.clone-to-directory)
        - name: spring-profile
          value: $(params.spring-profile)
      runAfter:
        - clone-sources
      taskRef:
        kind: Task
        name: jib-maven
      workspaces:
        - name: source
          workspace: source
    - name: image-scan
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: trivy-scan
      workspaces:
        - name: manifest-dir
          workspace: manifest-dir
    - name: create-redmine-issue
      params:
        - name: red-project-name
          value: $(params.red-project-name)
        - name: red-issue-subject
          value: $(params.application-name)
        - name: red-issue-tracker
          value: $(params.red-issue-tracker)
        - name: last-commit-message
          value: $(params.last-commit-message)
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(tasks.generate-id.results.build-id)
        - name: merge-title
          value: $(params.merge-title)
        - name: merge-description
          value: $(params.merge-description)
        - name: merge-date
          value: $(params.merge-date)
        - name: merge-commit-sha
          value: $(params.git-revision)
        - name: git-username
          value: $(params.git-username)
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: redmine-issue
      workspaces:
        - name: hro-redmine-config
          workspace: hro-redmine-config
  workspaces:
    - name: source
    - name: manifest-dir
    - name: hro-redmine-config
    - name: hro-tekton-logs

---

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pl-app-core-com-backend-approval
  namespace: devops-pipelines
spec:
  finally:
    - name: clean-workspace
      params:
        - name: subdirectory
          value: $(params.clone-to-directory)
      taskRef:
        kind: Task
        name: clean-workspace
      workspaces:
        - name: output
          workspace: source
    - name: report-result
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
      taskRef:
        kind: Task
        name: mm-send-result
  params:
    - name: build-stage
      type: string
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: git-username
      type: string
    - name: clone-to-directory
      type: string
    - name: image-url
      type: string
    - name: spring-profile
      type: string
    - name: gitops-url
      type: string
    - name: gitops-revision
      type: string
    - name: gitops-path
      type: string
    - name: deploy-manifest
      type: string
    - name: rollout-strategy
      type: string
    - name: pipelinerun-name
      type: string
    - name: mm-channel
      type: string
  tasks:
    - name: notify-pipeline-start
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
      taskRef:
        kind: Task
        name: mm-notify-start
    - name: generate-id
      params:
        - name: base-version
          value: $(params.build-stage)
      taskRef:
        kind: Task
        name: generate-build-id
    - name: clone-sources
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.clone-to-directory)
      runAfter:
        - generate-id
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
        - name: DIRECTORY
          value: $(params.clone-to-directory)
        - name: spring-profile
          value: $(params.spring-profile)
      runAfter:
        - clone-sources
      taskRef:
        kind: Task
        name: jib-maven
      workspaces:
        - name: source
          workspace: source
    - name: image-scan
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: trivy-scan
      workspaces:
        - name: manifest-dir
          workspace: manifest-dir
    - name: approval-task
      params:
        - name: pipeline
          value: $(params.pipelinerun-name)
        - name: description
          value: >-
            Approval Request from pipeline $(params.pipelinerun-name) for test
            environment
        - name: approvers
          value:
            - john@email.com
        - name: notifyOnSlack
          value: corecombackend
      runAfter:
        - build-image
      taskRef:
        apiVersion: tekton.automatiko.io/v1beta1
        kind: ApprovalTask
        name: approvaltask
    - name: update-gitops
      params:
        - name: git-revision
          value: $(params.git-revision)
        - name: gitops-revision
          value: $(params.gitops-revision)
        - name: deploy-manifest
          value: $(params.deploy-manifest)
        - name: gitops-path
          value: $(params.gitops-path)
        - name: gitops-url
          value: $(params.gitops-url)
        - name: rollout-strategy
          value: $(params.rollout-strategy)
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(tasks.generate-id.results.build-id)
      runAfter:
        - approval-task
      taskRef:
        kind: Task
        name: update-gitops
      when:
        - input: $(tasks.approval-task.results.decision)
          operator: in
          values:
            - 'true'
      workspaces:
        - name: gitops
          workspace: gitops
  workspaces:
    - name: source
    - name: gitops
    - name: manifest-dir


---

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pl-app-core-com-backend-deploy
  namespace: devops-pipelines
spec:
  finally:
    - name: report-result
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
      taskRef:
        kind: Task
        name: mm-send-result
    - name: save-pipelinerun-logs
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: pipeline-name
          value: $(params.pipeline-name)
      taskRef:
        kind: Task
        name: tekton-logging
      workspaces:
        - name: hro-tekton-logs
          workspace: hro-tekton-logs
  params:
    - name: build-id
      type: string
    - name: username
      type: string
    - name: image-url
      type: string
    - name: git-revision
      type: string
    - name: gitops-url
      type: string
    - name: gitops-revision
      type: string
    - name: gitops-path
      type: string
    - name: gitops-revision-dr
      type: string
    - name: gitops-path-dr
      type: string
    - name: deploy-manifest
      type: string
    - name: rollout-strategy
      type: string
    - name: pipelinerun-name
      type: string
    - name: pipeline-name
      type: string
    - name: mm-channel
      type: string
  tasks:
    - name: notify-pipeline-start
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
      taskRef:
        kind: Task
        name: mm-notify-start
    - name: update-gitops
      params:
        - name: git-revision
          value: $(params.git-revision)
        - name: gitops-revision
          value: $(params.gitops-revision)
        - name: deploy-manifest
          value: $(params.deploy-manifest)
        - name: gitops-path
          value: $(params.gitops-path)
        - name: gitops-url
          value: $(params.gitops-url)
        - name: rollout-strategy
          value: $(params.rollout-strategy)
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(params.build-id)
      runAfter:
        - notify-pipeline-start
      taskRef:
        kind: Task
        name: update-gitops
      workspaces:
        - name: gitops
          workspace: gitops
    - name: update-gitops-dr
      params:
        - name: git-revision
          value: $(params.git-revision)
        - name: gitops-revision
          value: $(params.gitops-revision-dr)
        - name: deploy-manifest
          value: $(params.deploy-manifest)
        - name: gitops-path
          value: $(params.gitops-path-dr)
        - name: gitops-url
          value: $(params.gitops-url)
        - name: rollout-strategy
          value: $(params.rollout-strategy)
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(params.build-id)
      runAfter:
        - update-gitops
      taskRef:
        kind: Task
        name: update-gitops
      workspaces:
        - name: gitops
          workspace: gitops
  workspaces:
    - name: gitops
    - name: hro-tekton-logs
