apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-app-dev
spec:
  controlNamespace: elastic-system
  fluentd:
    configReloaderImage:
      imagePullSecrets:
        - name: hero-reg
      repository: >-
        tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/config-reloader
      tag: v0.0.5
    image:
      imagePullSecrets:
        - name: hero-reg
      repository: >-
        tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/fluentd
      tag: v1.15-ruby3
    logLevel: debug

  
---

apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: logging-app-dev
spec:
  customParsers: |
    [MULTILINE_PARSER]
        name          hero-multiline-parser
        type          regex
        flush_timeout  2000
        rule          "start_state"   "^\[(\d{4}-\d{2}-\d{2}) (\d{2}:\d{2}:\d{2}:\d*)\]"    "cont"
        rule          "cont"          "^(\s+|[0-9]).*"                                      "cont"
        rule          "cont"          "^$"                                                  "cont"
        rule          "cont"          "^\|.*$"                                              "cont"
        rule          "cont"          "^}$"                                                 "cont"
        rule          "cont"          "/^\s+at.*/"                                          "cont"
    [MULTILINE_PARSER]
        name          hero-pipline-parser
        type          regex
        flush_timeout  30000
        rule          "start_state"   "^Pipeline still running ..*"                         "cont"
        rule          "cont"          "^PipelineRun is still running: .*"                   "cont"
        rule          "cont"          "^\[.*"                                               "cont"
        rule          "cont"          "^$"                                                  "cont"
  extraVolumeMounts:
    - destination: /hro/nas_dev
      readOnly: true
      source: /hro/nas_dev
  image:
    imagePullSecrets:
      - name: hero-reg
    repository: >-
      tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/fluent/fluent-bit
    tag: 2.1.8-debug
  inputTail:
    Exclude_Path: >-
      /hro/nas_dev/dev/hro_app/core-com-api-dev/log/*.*.log,
      /hro/nas_dev/test/hro_app/channel-prmadm-api-test/log/*.*.log
    Ignore_Older: 2d
    Path: >-
      /hro/nas_dev/dev/hro_app/core-com-batch-dev/log/*.log,
      /hro/nas_dev/prd/hro_devops/tekton/pl-app-core-sts-backend-build/*.log,
      /hro/nas_dev/prd/hro_devops/tekton/pl-app-core-sts-backend-deploy/*.log
    Path_Key: full_filename
    Buffer_Chunk_Size: 20m
    Buffer_Max_Size: 20m
    Skip_Long_Lines: "Off"
    Mem_Buf_Limit: 1Gi
    multiline.parser:
      - hero-multiline-parser
      - hero-pipline-parser
  logLevel: debug
  nodeSelector:
    nodeId: '18319608'
  flush: 30
  grace: 30
  resources:
    limits:
      memory: 2Gi

---

apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: co-app-channel-hmp-api-dev-es
  namespace: elastic-system
spec:
  elasticsearch:
    application_name: app-channel-hmp-api-dev
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    data_stream_enable: true
    data_stream_name: app-channel-hmp-api-dev-stream
    enable_ilm: true
    host: elasticsearch-master.elastic-system.svc.cluster.local
    include_timestamp: true
    index_date_pattern: YYYY-MM-DD
    index_name: app-channel-hmp-api-dev
    logstash_format: true
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: elasticsearch-master-credentials
    port: 9200
    request_timeout: 120s
    rollover_index: true
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    suppress_type_name: true
    user: elastic
    verify_es_version_at_startup: true

---

apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: co-app-channel-hmp-api-dev-s3
  namespace: elastic-system
spec:
  s3:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          key: access_key_id
          name: s3-auth
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          key: secret_access_key
          name: s3-auth
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    force_path_style: 'true'
    path: '%Y/%m/%d/${tag}'
    s3_bucket: hro-d-app-channel-hmp-api
    s3_endpoint: https://kr.object.private.fin-ncloudstorage.com
    s3_region: kr-standard

---

apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: cf-app-channel-hmp-api-dev
  namespace: elastic-system
spec:
  filters:
    - grep:
        regexp:
          - key: full_filename
            pattern: >-
              /^\/hro\/nas_dev\/dev\/hro_app\/(channel-hmp-api-dev)\/log\/.*.log$/
    - detectExceptions:
        languages:
          - java
        multiline_flush_interval: '5'
  globalOutputRefs:
    - co-app-channel-hmp-api-dev-es
    - co-app-channel-hmp-api-dev-s3
