apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-dev
spec:
  controlNamespace: elastic-system
  fluentd:
    logLevel: debug

---

apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: logging-dev
spec:
  bufferStorage:
    storage.checksum: 'off'
    storage.path: /buffer
    storage.sync: normal
  bufferStorageVolume:
    hostPath:
      path: /fluentbit/buffer
  customParsers: |
    [PARSER]
        Name hero-log-parser
        Format regex
        Regex ^\[(?<time>[^ ].*)\]\[(?<pid>[^ ]*)\]\s+(?<type>[A-Z]+)\s+(?<app>([a-z].*))\s+\[(?<code>[0-9]{2,4})\]-\[(?<message>.*)
        Time_key time
    [MULTILINE_PARSER]
        name          hero-multiline-parser
        type          regex
        flush_timeout 1000
        rule      "start_state"   "/^\[\d{4}-\d{2}-\d{2}\s+.*/"                         "cont"
        rule      "cont"          "^(\s+|\||[0-9]).*"                                   "cont"
        rule      "cont"          "^$"                                                  "cont"
        rule      "cont"          "^}$"                                                 "cont"
  extraVolumeMounts:
    - destination: /hro/nas_dev
      readOnly: true
      source: /hro/nas_dev
  inputTail:
    Exclude_Path: >-
      /hro/nas_dev/dev/hro_app/core-com-api-dev/log/*.*.log
    Mem_Buf_Limit: 100MB
    Path: >-
      /hro/nas_dev/dev/hro_app/core-com-api-dev/log/*.log
    Path_Key: filename
    multiline.parser:
      - java
      - hero-multiline-parser
    storage.type: filesystem
  logLevel: debug
  positiondb:
    hostPath:
      path: /fluentbit/position
  resources:
    limits:
      cpu: 500m
      memory: 1500M

---

apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: co-core-com-api-dev-es
  namespace: elastic-system
spec:
  elasticsearch:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    host: elasticsearch-master.elastic-system.svc.cluster.local
    include_timestamp: true
    index_name: app-core-com-api-dev
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: elasticsearch-master-credentials
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    suppress_type_name: true
    user: elastic

---

apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: co-core-com-api-dev-s3
  namespace: elastic-system
spec:
  s3:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          key: access_key_id
          name: s3-auth
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          key: secret_access_key
          name: s3-auth
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    force_path_style: 'true'
    path: '%Y/%m/%d/${tag}'
    s3_bucket: hro-d-core-com-api
    s3_endpoint: https://kr.object.private.fin-ncloudstorage.com
    s3_region: kr-standard

---

apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: cf-core-com-api-dev
  namespace: elastic-system
spec:
  filters:
    - detectExceptions:
        multiline_flush_interval: '1'
    - parser:
        key_name: log
        parse:
          expression: >-
            ^\[(?<time>[^ ].*)\]\[(?<pid>[^
            ]*)\]\s+(?<type>[A-Z]+)\s+([a-z]|\.)*[A-Z]\w+\s+\.*\[\d*\]-\[(?<app>\w+-\w+-\w+),(?<traceid>\w*)\]-(?<message>.*)
          type: regexp
        reserve_data: true
        reserve_time: true
    - record_transformer:
        records:
          - stage: dev
    - grep:
        and:
          - regexp:
              - key: app
                pattern: /hro-com-backend/
              - key: pid
                pattern: /-8070-/
  globalOutputRefs:
    - co-core-com-api-dev-es
    - co-core-com-api-dev-s3