apiVersion: batch/v1
kind: CronJob
metadata:
  name: sw-log-backup-job
  namespace: elastic-system
spec:
  schedule: 0 1 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: script-volume
              configMap:
                name: sw-log-s3-backup-script
                defaultMode: 511
            - name: hro-app
              nfs:
                server: 169.254.0.20
                path: /n3031818_nkshrod/hro/dev/hro_app
          containers:
            - name: sw-log-s3-backup
              image: >-
                tbd5d100.private-ncr.fin-ntruss.com/k8s/dev/devops/awscli:1.15.85-5
              command:
                - /home/devops/works/run-backup.sh
              env:
                - name: ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-auth
                      key: access_key_id
                - name: SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-auth
                      key: secret_access_key
              resources: {}
              volumeMounts:
                - name: script-volume
                  mountPath: /home/devops/works
                - name: hro-app
                  mountPath: /hro_app/
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: sw-backup
          serviceAccount: sw-backup
          automountServiceAccountToken: true
          securityContext: {}
          imagePullSecrets:
            - name: hero-reg
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sw-log-s3-backup-config
  namespace: elastic-system
data:
  edms-ap-dev: hro-d-sw-edms-ap
  fep-ap-dev: hro-d-sw-fep-ap
  mci-ap-dev: hro-d-sw-mci-ap
  rept-ap-dev: hro-d-sw-rept-ap
  sso-ap-dev: hro-d-sw-sso-ap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sw-log-s3-backup-script
  namespace: elastic-system
data:
  run-backup.sh: >-
    #!/bin/bash

    aws configure set aws_access_key_id $ACCESS_KEY_ID --profile default \
      && aws configure set aws_secret_access_key $SECRET_ACCESS_KEY --profile default \
      && aws configure set region kr-standard --profile default \
      && aws configure set output "json" --profile default
      
    CONFIGMAP_DATA=$(kubectl get configmap sw-log-s3-backup-config -n
    elastic-system -o json | jq -r '.data | to_entries[] | "\(.key):\(.value)"')

    echo "$CONFIGMAP_DATA" | while read line; do
      KEY=$(echo $line | cut -f1 -d:)
      VALUE=$(echo $line | cut -f2 -d:)
      
      SYNC_COMMAND=$(aws --endpoint-url=https://kr.object.fin-ncloudstorage.com s3 sync /hro_app/$KEY/log/ s3://$VALUE)
      
      echo "$SYNC_COMMAND"
      
    done
