apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-backup-job
  namespace: gitlab
spec:
  schedule: 0 23 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: script-volume # ConfigMap으로 Mount
              configMap:
                name: gitlab-backup-job
                defaultMode: 511
          containers:
            - name: gitlab-backup
              image: >-
                bitnami/kubectl:1.25.8-debian-11-r6
              command:
                - /bin/bash
              args:
                - '-c'
                - /usr/bin/run-backup.sh
              resources: {}
              volumeMounts:
                - name: script-volume
                  mountPath: /usr/bin
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: gitlab-backup
          serviceAccount: gitlab-backup
          automountServiceAccountToken: true
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-backup-job
  namespace: gitlab
data:
  run-backup.sh: |-
    #!/bin/bash
    # 설치된 gitlab-toolbox에 있는 backup-utility를 이용해 S3 Bucket에 저장
    kubectl -n gitlab exec -i -c toolbox \
      $( kubectl get pod -n gitlab -l app=toolbox --no-headers -o custom-columns=":metadata.name" ) \
      -- /bin/sh <<EOF
      aws configure set aws_access_key_id B8706A69B7********** --profile default \
      && aws configure set aws_secret_access_key 7C48BD41C67993AD8B693A6B335EFB********** --profile default \
      && aws configure set region kr-standard --profile default \
      && aws configure set output "json" --profile default
      export BACKUP_BUCKET_NAME=hro-d-devops-gitlab-backups
      backup-utility --s3tool awscli --aws-s3-endpoint-url https://kr.object.private.fin-ncloudstorage.com --aws-region kr-standard
    EOF
